### ISSUE TITLE
yarn run serve -> Cannot destructure property 'parser' of 'options' as it is undefined.

### ISSUE THREAD

**Issue by LordOfInternet** [spraakbanken/swell-editor#196]
After running 'yarn' I run 'yarn run serve'.

This throws the above mentioned error (Cannot destructure property 'parser' of 'options' as it is undefined.)

Full stack trace:
_yarn run serve_
yarn run v1.22.19
$ parcel (ts-node src/generate_index.ts {App:-Editor})
Server running at http://localhost:1234
**/home/path/to/project/index.html: Cannot destructure property 'parser' of 'options' as it is undefined.** 
at Object.MakeTranspileAsset (/home/path/to/project/node_modules/parcel-plugin-typescript/build/frontend/assets/classes/transpile.js:7:13)
at new module.exports (/home/path/to/project/node_modules/parcel-plugin-typescript/frontend/assets/forked.js:6:43)
at Parser.getAsset (/home/path/to/project/node_modules/parcel-bundler/src/Parser.js:85:12)
at HTMLAsset.addURLDependency (/home/path/to/project/node_modules/parcel-bundler/src/Asset.js:116:8)
at HTMLAsset.proccessSingleDependency (/home/path/to/project/node_modules/parcel-bundler/src/assets/HTMLAsset.js:99:26)
at /home/path/to/project/node_modules/parcel-bundler/src/assets/HTMLAsset.js:166:43
at traverse (/home/path/to/project/node_modules/posthtml/lib/api.js:105:26)
at traverse (/home/path/to/project/node_modules/posthtml/lib/api.js:111:5)
at traverse (/home/path/to/project/node_modules/posthtml/lib/api.js:105:17)
at traverse (/home/path/to/project/node_modules/posthtml/lib/api.js:111:5)

Any help would be appreciated. Thank you.

**Comment by arildm** [comment]
Until I can put time into looking into this, here's my spontaneous thoughts:

- Your result on Ubuntu looks to me like you might be using another version of Node.js than the code is written for. You might have more success running an older version, perhaps 10? [nvm](https://github.com/nvm-sh/nvm) is a useful utility for switching between Node.js versions. I think you will need to install Yarn anew for each Node.js version.
- We haven't been testing this on Windows, so the codebase may not be compatible. I would recommend Ubuntu over Windows.

**Comment by LordOfInternet** [comment]
Understandable. Thank you. I will give it a try.

**Comment by LordOfInternet** [comment]
I've tried using (latest) node version 8, 10, 11 and 12.

Using v8 it throws and error; expected version is 10 or more.
Using every other version (listed above), the error changes slightly to:
_/home/path/to/project/index.html: Cannot destructure property `parser` of 'undefined' or 'null'._

The stack trace remains the same.

Once you get back to it, I would appreciate a heads up.
Thank you

**Comment by arildm** [comment]
I have just pushed a few commits, including an upgrade of the Parcel dependency, which might fix your problem. I tested this with Node 16. Could you check if that works for you?
